spring:
  jpa:
    ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/mercadolivro?createDataBaseIfNotExist=true
    username: postgres
    password: Douglas12957534@
    jackson:
      default-property-inclusion: non_null
